// generated by "sampctl package generate"

#include "Silent_teleport.inc"

main() {
	// write tests for libraries here and run "sampctl package run"
}

public OnPlayerJackTeleporter(playerid, teleporterid, vehicleid)
{
	SendClientMessageToAll(-1, "A jack teleport process happened");
	return 1;
}